version: '3.8'

services:
  runner:
    image: s1248/github-self-hosted-runners:latest
    environment:
      # URL và Labels sẽ do người dùng nhập vào
      - ACTIONS_RUNNER_INPUT_URL=${ACTIONS_RUNNER_INPUT_URL}
      - ACTIONS_RUNNER_INPUT_LABELS=${ACTIONS_RUNNER_INPUT_LABELS:-self-hosted-runners,ubuntu24}
    
    # Gắn secret có tên 'runner_token' vào container
    secrets:
      - runner_token

    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

# Khai báo rằng stack này sử dụng một secret đã tồn tại sẵn
secrets:
  runner_token:
    external: true