name: Build and Publish Public Runner Image

# Kích hoạt workflow khi có push vào nhánh 'main'
on:
  push:
    branches:
      - main

# Cấp quyền cho workflow để có thể ghi package
permissions:
  contents: read
  packages: write

jobs:
  build-and-publish:
    name: Build and Publish to GHCR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          # GITHUB_TOKEN được GitHub Actions tự động tạo ra với quyền đã được cấp ở trên
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags and labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          # Đặt tên image theo định dạng của GitHub Container Registry
          images: ghcr.io/${{ github.repository }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # Sử dụng tags đã được tạo tự động từ bước metadata
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}